hypothesis/h-periodic

Dockerfile
Jenkinsfile
version.py

Previously this has been done by Skyliner. Now that we're moving to Beanstalk we have do build our own container and push it to the registry.

Build and push docker image with Jenkins

---

Dockerfile
hperiodic.py
requirements.txt

This PR is a prerequisite to adding SQS support extracted from https://github.com/hypothesis/h-periodic/pull/8. It upgrades the Alpine Linux base image and Celery to the same versions used in h. Additionally I have refactored the Docker image to use the same pattern as h's Dockerfile to avoid leaving built-time only dependencies in the final image.
----
To test this PR, or any for this project, manually:
1. Edit `hperiodic.py` and shorten the schedule for one of the tasks down to a few seconds
2. Build a Docker image with `docker build -t {some tag} .`
3. Run the Docker container `docker run -it -e 'BROKER_URL=amqp://guest:guest@rabbitmq:5672//' --link rabbitmq {tag name}`
4. Run the h dev server
5. Check that every few seconds (whatever schedule was set in step 1) the h dev server prints …

Update Alpine and Celery

---

h_periodic/beat.py

If h's Celery workers had an outage then h-periodic would continue
piling up instances of each periodic task in Rabbit. For example one
`"sync-annotations"` task every minute while h was down. When the
workers came back up they would process all of the queued periodic tasks
at once, as fast as they could. So you'd get lots of
`"sync-annotations"` tasks being run at once by all the workers.
Potentially thrashing the system.
Change the periodic tasks to expire after a few seconds if not taken by
a worker. After an h outage, each task will get processed again the next
time it's scheduled after the workers come back, rather than piling up
many instances of each task on the queue.
I couldn't see a way to do this without having to repeat the options for
each task. I tried changing it to have an …

Expire periodic tasks so they don't pile up

---

conf/development.ini
conf/production.ini
h_periodic/app.py
h_periodic/views/status.py
tests/unit/h_periodic/views/status_test.py
tests/unit/sanity_test.py

In order to be able to support checkmate and h brokers and beats separately we need to report on them both individually.
This means we want to know how one is getting on if the other is down. This PR makes way for that by separating out the `h` status and not failing on the first thing which is wrong, but reporting all the separate failures and rolling them up instead.
* In `h` do `make services`
* In `h-periodic` do `make dev`
* Visit: http://localhost:8080/_status
* You should see everything "ok"
Bad connection:
* Run `docker stop h_rabbit_1`
* Visit: http://localhost:8080/_status
* You should see the status as down, because the connection is down
Bad beat:
* Stop `h-periodic`
* Comment out the beat section in `supervisord-dev.conf`
* Run `make dev`
* Visit: …

Separate status reporting out for `h` and return all failures rather than the first

---

.gitignore
README.markdown
conf/supervisord-dev.conf
conf/supervisord.conf
h_periodic/checkmate_beat.py
h_periodic/h_beat.py
h_periodic/views/status.py
tests/unit/h_periodic/test_app.py
tests/unit/h_periodic/test_checkmate_beat.py
tests/unit/h_periodic/test_h_beat.py
tests/unit/h_periodic/views/status_test.py
tox.ini

Needs to be rebased on top of:
* https://github.com/hypothesis/h-periodic/tree/separate-status-reporting
* https://github.com/hypothesis/h-periodic/tree/separate-h-beat
This PR:
* Adds a new beat for Checkmate
* Includes the status in the status page
* Will report as:
* 200 - "ok" if both are up
* 200 - "degraded" if one is down
* 500 - "down" if both are down
* Expands linting and formatting to the tests
* Gets 100% coverage by including and "no cover"-ing files
* AWS doesn't care what content we send, so "degraded" and "ok" are basically the same
* Ian says we can script it to parse and understand it if we want to
To test the status page:
* Setup and take down the services in `h` and `checkmate` and observe the changes
* Comment in and out the various beats and see the changes
To test …

Add checkmate beat and include it in the status page

---

conf/supervisord-dev.conf
conf/supervisord.conf
h_periodic/checkmate_beat.py

The `h` beat works by happening to line up with the default, but checkmate is different, so it doesn't work.
* In Checkmate run `make services dev`
* Run `make dev`
* See that tasks are being queued
* In Checkmate see nothing ~(WHY?) - This is actually doing what it should, if you make the task touch a file, you can see it's touched, but no log output comes out anymore. What's changed?~ - Fixed in https://github.com/hypothesis/checkmate/pull/47

Fix checkmate celery queue to match the settings in Checkmate

---

h_periodic/checkmate_beat.py

For: https://github.com/hypothesis/checkmate/issues/37
I wanted to use crontab here so we don't automatically do this as soon as we are deployed, but on a reliable schedule. This will be
annoying the first time, but useful after.
Currently the schedules are every day for the full resync at midnight, and every 30 mins for the update, offset by 15 mins to make sure we don't try and do both at once.
* In checkmate run `CHECKMATE_BLOCKLIST_URL=<s3 url> make dev` (so it doesn't whine about the bad URL)
* Hack the schedule to run more frequently or on a time about to come up
* `make dev`
* You should see the task picked up by Checkmate, but it doesn't lot a lot about it

Add configuration for syncing URLHaus

---

start.sh

This is a pre-modern script, should have been deleted when h-periodic was modernised

Remove the start.sh script

---

README.markdown
h_periodic/h_beat.py
tests/unit/h_periodic/h_beat_test.py
tests/unit/h_periodic/sanity_test.py
tox.ini

Depends on https://github.com/hypothesis/h-periodic/pull/49
We [don't want h-periodic for h-qa](https://github.com/hypothesis/playbook/issues/436).
Unfortunately we can't just get rid of h-periodic-qa entirely as previously planned, because we *do* want h-periodic for checkmate-qa.
I don't think just removing the `BROKER_URL` envvar from h-qa will work. h's code isn't really designed to disable Celery workers if there's no `BROKER_URL`. Rather, it assumes that you do want Celery workers and uses a default broker URL if none is set: https://github.com/hypothesis/h/blob/36a266b1d5ddbb7bd00fd888766c391f3a3da810/h/celery.py#L24-L27
Also, what would happen if h-periodic-qa was still emitting periodic tasks for h-qa workers to consume, but h-qa wasn't running any connected workers? I think this …

Add DISABLE_H_BEAT envvar

---

h_periodic/checkmate_beat.py

Due to `async` being a reserved word in Python 3.7, we can't call a module that. So we have to rename it.
**This must be released in sync with the changes in Checkmate:** https://github.com/hypothesis/checkmate/pull/309

Update the name of the tasks in Checkmate

---

requirements/dev.txt
requirements/lint.txt
requirements/tests.txt
tox.ini

For: https://github.com/hypothesis/tox-pip-sync/issues/11
This also recompiles the dependencies afterward using the technique I've been using on the projects done later in case any changes are found. 
This process is to:
* `rm requirements/*.txt`
* `git checkout/requirements.txt` - To preserve the set in live
* `hdev requirements`
This also removed an unnecessary `-e .` which just slows things down.

Replace `tox-pip-extensions` with `tox-pip-sync`

---

.github/dependabot.yml

For: https://github.com/hypothesis/product-backlog/issues/1209
I don't know there's a way to test this without merging it. If we merge it and dependabot works as expected we should get a PR for: `3.8.10-alpine3.14` depending on how/if dependabot handles `10-alpine3.1.4` as a patch number. (See https://hub.docker.com/_/python)
For details of the format see: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore
Also side note, Pycharm is a total dude and has auto complete and schema checking for the dependbot YAML config file, which I was not expecting.

Add dependabot monitoring of docker images (patch versions only)

---

.gitignore
README.markdown
conf/supervisord-dev.conf
conf/supervisord.conf
h_periodic/lms_beat.py
tests/unit/h_periodic/lms_beat_test.py
tox.ini

Needs https://github.com/hypothesis/lms/pull/4142 merged first
`LMS_BROKER_URL` already set on prod/qa and Canada environments.
- Checkout https://github.com/hypothesis/lms/pull/4142 on LMS and `make services dev`
- Change the perodicity of the task here to something like `minutes=1`, `make dev`
- See the executing of the task on LMS's `make dev` logs.

New celery beat for LMS tasks

---

h_periodic/lms_beat.py

The beat process gets restarted often, more than once a day, so longer
schedules never get the change of running for the first time.
The rotate keys task itself won't be affected by running more often as
it's based on the age of the keys on the DB.
Some logs of a restart:
```
Jun 29 04:43:51 h-periodic-qa_i-013a4a4e17dfd8307 eb-1ea7a0a3ff69-stdouterr.log 2022-06-29 07:56:04,592 INFO supervisord started with pid 1
Jun 29 04:43:51 h-periodic-qa_i-013a4a4e17dfd8307 eb-1ea7a0a3ff69-stdouterr.log 2022-06-29 07:56:05,594 INFO spawned: 'logger' with pid 14
Jun 29 04:43:51 h-periodic-qa_i-013a4a4e17dfd8307 eb-1ea7a0a3ff69-stdouterr.log 2022-06-29 07:56:05,598 INFO spawned: 'checkmate-beat' with pid 15
Jun 29 04:43:51 h-periodic-qa_i-013a4a4e17dfd8307 eb-1ea7a0a3ff69-stdouterr.log 2022-06-29 …
```

Run the LMS rotate keys task more frequently

---

requirements/checkformatting.in
requirements/checkformatting.txt
requirements/coverage.in
requirements/coverage.txt
requirements/dev.in
requirements/dev.txt
requirements/format.in
requirements/format.txt
requirements/lint.in
requirements/lint.txt
requirements/tests.in
requirements/tests.txt
tox.ini

**Developers will have to `rm -rf .tox` in their dev envs after merging this** if they see `command not found: pip-sync-faster`.
Simplify our development tooling by removing the `tox-pip-sync` plugin in favour of calling [`pip-sync-faster`](https://github.com/hypothesis/pip-sync-faster) directly from `tox.ini`.
Also add the [`tox-faster`](https://github.com/hypothesis/tox-faster) plugin to `tox.ini`: `tox-faster` is a standalone implementation of a small `tox` speedup that was previously implemented in `tox-pip-sync`.
We did this in LMS a while ago and haven't noticed any problems there:
https://github.com/hypothesis/lms/pull/4191/files
Details
-------
* `pip-sync-faster` is added to all the `requirements/*.in` files (except the production `requirements/requirements.in`). …

Remove `tox-pip-sync`

---

.github/workflows/deploy.yml

Since h-periodic doesn't have a public URL or any other URL to go to in
order to test it, use the URLs of h-periodic's QA, production and Canada
Papertrail groups for the environment URLs. This means you can click on
the environment URL in GitHub and be taken straight to the Papertrail
logs.

Add GitHub environment URLs

---

.github/workflows/ci.yml

The `ci.yml` workflow needs to be callable by other workflows because `deploy.yml` tries to call it.

Attempt to fix `deploy.yml`

---

h_periodic/lms_beat.py

The previous value of 1000 was just an arbitrary number chosen by me and I think it's probably too large: it could take the task a long time to send 1000 emails.
In future we may split the actual email sending out into a separate task which sends one email per task instance. If we do that then we may be able to increase the batch size again.

Reduce LMS email digests batch size to 50

---

h_periodic/lms_beat.py

These are all the default settings except for `durable=False` and we actualy want it to be `durable=True` (the default) so just remove these.

Remove unnecessary exchange and queue settings

---

h_periodic/checkmate_beat.py
h_periodic/h_beat.py
h_periodic/lms_beat.py

We want our exchanges and queues to be `durable=True` (the default) not
`durable=False` unless we really have a good reason for using `False`.
`task_serializer="json"` is the default.

Remove unnecessary Celery config

---

h_periodic/lms_beat.py

Fixes https://github.com/hypothesis/h-periodic/issues/320
We'd like LMS to generate its daily instructor email digests later in
the day so that if the generation triggers an alert it doesn't wake UK
engineers from sleep.
See <https://hypothes-is.slack.com/archives/C074BUPEG/p1687340914305749?thread_ts=1687325831.540209&cid=C074BUPEG>
for considerations about the timing: I think we want a time period of a
few hours in which to generate and send all the emails. With rate
limiting (https://github.com/hypothesis/lms/pull/5512) I think it could
take over an hour to get through all the emails (at our current volume)
assuming there aren't any retries. Retries can add a delay of three
hours. Ideally we'd like the emails to be in people's inboxes before say
6am EST (10am UTC) although I think a …

Schedule `send_instructor_email_digests()` later in the day

---

h_periodic/h_beat.py

The `*` overrides anything that follows.

Fix fill pk schedule to run on the intended times

---

h_periodic/h_beat.py

Now that the batch size is 5000 run it more frequently
Soft timeout for the task is 2 minutes, hard limit is 4, so we should be within the limits. In any case there's no issue of running more than one of these at the same time if it come to that.

Increase H pk fill up frequency to run every 5 minutes

---

h_periodic/h_beat.py

We've been seeing a number of timeouts for this tasks. Reducing the number drastically to try to get the number of failed task to 0.
Task monitoring: https://one.newrelic.com/nr1-core/apm-features/transactions/MTM4NTI4M3xBUE18QVBQTElDQVRJT058MjI2ODg2MzE?account=1385283&duration=604800000&state=fe611650-259d-7fd0-114a-8a0f8f31d672

Decrease batch size for the H.annotation pk fill up task

---

h_periodic/h_beat.py

4AM UTC seem to be the lowest activity period now, before the report refresh and the backup.
Starting with a small batch size.

Add task to fill the AnnotationSlim table

---

h_periodic/h_beat.py

Timeout on the celery task is 2 minutes. One run every 4 should not cause any issues in case one fails.

Run the fill annotation task every 4 minutes

---

h_periodic/h_beat.py

Start the day with a smaller batch size and switch to a bigger one after 1 hour.
Run the task every 3 minutes instead of 4.

Daily start of the fill annotation with a smaller batch size

---

h_periodic/h_beat.py

Start one hour earlier and finish one hour later.
Make the first batch of the day even smaller. We have hit the 2 minutes limit on the very first batch today. The rest were all fine. Hopefully the smaller batch avoid that first error.

Run the slim task two more hours a day

---

h_periodic/h_beat.py

After the change in the query the behaviour regarding the first batch seems to still be true so we are keeping the smaller first batches in the morning.
After that  the task seems to finish much faster so we are extending the period when the task runs, make it more frequent and with a bigger batch.

Further increase fill up task speed

---

h_periodic/lms_beat.py

Decrease the `batch_size` of the `send_instructor_email_digest_tasks()` Celery task.
This is because I want to try decreasing the task's `batch_size` and correspondingly increasing its `rate_limit` (see https://github.com/hypothesis/lms/pull/5827) to see what effect that has on performance, with an eye towards potentially removing the batching feature altogether in order to simplify adding future features to this code.

Decrease `send_instructor_email_digest_tasks()` batch size

---

h_periodic/h_beat.py

The dates here take into account the progress made so far and move the window forward a few months to see the impact on performance.
In theory a very big window will degrade performance significantly as it will need to visit more annotations.

Include the since/until parameters for H slim task

---

h_periodic/lms_beat.py

Decrease the batch size of the `send_instructor_email_digests()` Celery
task again, this time decreasing it 10x from `10` to `1`.
This is to enable us to see whether we could get away with removing the
batching feature. We'll attempt to maintain the speed at which emails
are generated at about the same rate by simultaneously increasing the
task's rate limit, see: https://github.com/hypothesis/lms/pull/5841
Slack thread: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1700130444868909?thread_ts=1699980253.387059&cid=C1MA4E9B9

Decrease `send_instructor_email_digests` batch size again

---

h_periodic/lms_beat.py

Needs to be deployed at the same time as <https://github.com/hypothesis/lms/pull/5897> and not during the daily email digest generation time.

Remove the batch_size argument

---

requirements/checkformatting.txt
requirements/coverage.txt
requirements/dev.txt
requirements/format.txt
requirements/functests.txt
requirements/lint.txt
requirements/prod.txt
requirements/template.txt
requirements/tests.txt

This is the result of running:
`make requirements --always-make args='--upgrade'`
Non top level dependencies can become outdated as dependabot doesn't send PR for those.
On top of that upgrading single packages with all the existing constraints might make impassible to satisfy all constraints.
This approach makes sure we are up to date with all our dependencies as specified on the .in files but without considering any constraints in the .txt files.

Upgrade python dependencies

---

h_periodic/h_beat.py

---
This is based on a different approach.
Jobs are added to the queue in H, using the admin pages and this job process a number of rows each time.
Technically we don't have to make expensive queries to process them, just query annos by ID. We still might hit different bottlenecks as we progress.

Process jobs for filling up the slim table more often

---

h_periodic/h_beat.py

This reverts commit 92811a26eaa8069cc69e0986485d44e2f7a933b2,
the `purge_deleted_users()` task will now be run hourly again instead of
every minute.

Revert "Run purge_deleted_users() every minute"

---

h_periodic/h_beat.py

Running the `purge-deleted-annotations` and `purge-deleted-users` tasks
only hourly means that it can take quite a while after deleting an
annotation or user before that data is actually deleted from our DB,
especially if there are a lot of annotations or users to be purged so
that we have to wait for the task to run multiple times (so multiple
hours) to get through them all.
Run these two tasks every 5 mins instead.
Looking at these two tasks in New Relic they take only milliseconds to
run, so running them every few minutes shouldn't be a problem.
https://onenr.io/07j9P3z4ARO
https://onenr.io/0VRVdEG01Qa

Run some h tasks more frequently

---

h_periodic/h_beat.py

This is so that I can test New Relic's "lost signal" alert for the num.
deleted annotations metric.
This commit will be reverted after testing.

Temporarily remove the `report_num_deleted_annotations()` task

---

h_periodic/lms_beat.py

While the goal is to run this only at the start of every month a more frequent schedule is useful now for:
- Debugging any issue without long waits
- Start backfilling reports for existing organizations

Schedule more frequently usage reports

---

h_periodic/lms_beat.py

- Limit increased to 2
This will just make the generation faster
- Set backfill to 2
Now we have a few organizations that have completed the backfill going back to the earliest report they'll ever have.
To focus on a different type of metabase report (ie a report that queries the data generated here) it would more useful to have more organizations with reports rather that just a few with all their history.
Setting backfill to 2 will just generate 3 reports per organization (the last one plus two past ones) before moving to the next organization.

Change parameters for LMS monthly report task

---

h_periodic/lms_beat.py

We already have at least one report for each organization, time to finish the job of the backfill.

Backfill all organization usage reports

---

h_periodic/lms_beat.py

Last PR for:
- https://github.com/hypothesis/lms/issues/6159
Call the LMS hubpost.export_companies_contract_billables daily.
We call it one hour after the refresh_hubpost_data task but there's no need to synchronize between the two, we just need to call them both regularly.

Schedule daily export of company data to HubSpot

---

h_periodic/__init__.py
h_periodic/_version.py

The releases feature is useful in itself, and this should also stop the
"discarded session update because of missing release" messages that
`sentry_sdk` is logging all the time.

Enable Sentry's "releases" feature
