Jenkinsfile

This updates the Jenkinsfile to use the helper functions defined in our [pipeline library][1], as well as introducing some control flow (explained below) to ensure that deployments happen as we expect.
[1]: https://github.com/hypothesis/pipeline-library
For more information on the `buildApp`/`releaseApp`/`deployApp` helper functions, see the [pipeline library][1] documentation.
The other important change in this commit is the introduction of flow control using `milestone` and `lock` pipeline steps. These are introduced to ensure that deployments happen in-order and one at a time (to each environment) when multiple builds occur in parallel on Jenkins. They achieve this as follows:
The `milestone()` steps indicate points in the build where if a build started later reaches a particular …

Update Jenkinsfile to use pipeline library

---

Jenkinsfile

The responsibility to lock deployment environments has moved into the
deployment job itself.

Remove locking steps

---

hperiodic.py

~To be merged after hypothesis/h#4593 gets merged.~

Periodically clean up expired authentication codes

---

h_periodic/beat.py

Just while I'm testing something...

Temporarily remove the sync_annotations task

---

h_periodic/beat.py

Reverts hypothesis/h-periodic#24

Revert "Temporarily remove the sync_annotations task"

---

h_periodic/beat.py

See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1603736751231600?thread_ts=1603385554.156100&cid=C4K6M7P5E

Reduce the sync-annotations limit to 5000

---

Makefile
requirements/compile.sh

This to allow us to update the requirements easily (I'm about to add some test stuff)

Add the scripts to allow easy `make requirements`

---

.gitignore
README.markdown
conf/supervisord-dev.conf
conf/supervisord.conf
h_periodic/checkmate_beat.py
tests/unit/h_periodic/checkmate_beat_test.py
tox.ini

Reverts hypothesis/h-periodic#68. This did not fix the issue, see: https://hypothes-is.slack.com/archives/CR3E3S7K8/p1616689236047100?thread_ts=1616581242.031600&cid=CR3E3S7K8

Revert "Remove Checkmate support"

---

requirements/dev.txt
requirements/lint.txt
requirements/requirements.txt
requirements/tests.txt

For: https://github.com/hypothesis/h/issues/6596

Update to Celery 5.1

---

.github/workflows/continuous-integration.yml

This should be faster, but might also fix a problem we have in CI now.

Upgrade the checkout function to V2

---

README.markdown

This commit delivers a small update to the README file. The change was
made to test out the CI workflow.

Testing CI workflow.

---

Jenkinsfile

This commit enables h-periodic deployments for our Canadian environment

Enable h-periodic deployments for Canada

---

Jenkinsfile
tests/.pylintrc

1. Updated Jenkinsfile to use the onlyOnMain function instead of
onlyOnMaster
2. Updated tests/.pylintrc to target the MAIN branch instead of MASTER

Renamed default branch to main

---

.github/workflows/continuous-integration.yml
.github/workflows/elasticbeanstalk.yml
.github/workflows/release.yml

**elasticbeanstalk.yml**
A manually triggered workflow that performs `redeploy`, `deploy` and
`sync-env` operations against an Elastic Beanstalk application.
**release.yml**
Manages the process of releasing code updates. Triggered by an on-push
event to the main branch.
**continuous-integration.yml**
Added `workflow_call` to the list of triggers that start the workflow.
---
Part of the work towards: https://github.com/hypothesis/playbook/issues/929

GitHub Actions - Deployment Workflows

---

README.markdown

Demonstrating GitHub workflow to the team

Demonstrating GitHub Release Workflow

---

.github/workflows/codeql.yml

Added the default CodeQL GitHub Action to perform static code analysis.
https://github.com/github/codeql-action/

Created CodeQL Workflow

---

.cookiecutter/cookiecutter.json
.cookiecutter/includes/conf/supervisord-dev.conf.json
.cookiecutter/includes/conf/supervisord.conf.json
conf/supervisord-dev.conf
conf/supervisord.conf

Depends on https://github.com/hypothesis/cookiecutters/pull/91

Apply the cookiecutter to Supervisor config files

---

h_periodic/lms_beat.py

Depends on https://github.com/hypothesis/lms/pull/5164

Add email digests periodic task

---

h_periodic/lms_beat.py

Depends on https://github.com/hypothesis/lms/pull/5364
Fixes https://github.com/hypothesis/lms/issues/5348

Periodically delete expired `task_done` rows

---

h_periodic/h_beat.py

Start running it every hour between 8 and 10 UTC with a batch of 1000.
We can modify accordingly later after seeing real performance numbers in production.

Add the schedule for h.tasks.annotations.fill_pk_and_user_id

---

h_periodic/h_beat.py

Run it every 15 minutes. Finish earlier in the day

Change the fill up task schedule

---

h_periodic/h_beat.py

With this we'll be up to around 0.5M annos a day.

Further move the start time of the anno pk fill upt task up

---

h_periodic/h_beat.py

Currently too slow, disable it until we found the underlying issue.

Disable the annotation.pk fill up task

---

h_periodic/h_beat.py

Matching the change over https://github.com/hypothesis/h/pull/8438
This task will only check if there are any new jobs to be processed. Adding jobs here is done in H's admin pages.

Schedule the new task to sync annotation slim jobs

---

h_periodic/h_beat.py

Depends on https://github.com/hypothesis/h/pull/8700

Add `purge_deleted_users()` task to h

---

h_periodic/h_beat.py

Reverts hypothesis/h-periodic#452

Revert "Temporarily remove the `report_num_deleted_annotations()` task"

---

requirements/typecheck.txt

The result of running:
make --always-make requirements/typecheck.txt

Fix typecheck requirements.txt file

---

h_periodic/lms_beat.py

First part of the plan described here:
https://github.com/hypothesis/lms/pull/6332

Schedule monthly usage report generation

---

h_periodic/lms_beat.py

This runs the task daily instead of every minute for one hour

Include the minute parameter for crontab entries missing it

---

h_periodic/lms_beat.py

Start once a day at first, we'll ramp it up as we start getting data.
For:
- https://github.com/hypothesis/lms/issues/6185

Schedule fetching roster

---

h_periodic/lms_beat.py

For:
- https://github.com/hypothesis/lms/issues/6185
After the first successfully sync start running it more frequently

Schedule roster fetching hourly

---

h_periodic/lms_beat.py

For:
- https://github.com/hypothesis/lms/issues/6185

More frequent roster fetching

---

h_periodic/checkmate_beat.py

Refs https://github.com/hypothesis/checkmate/issues/921

Remove checkmate sync blocklist

---

h_periodic/lms_beat.py

Related to:
https://github.com/hypothesis/lms/pull/6832
Runs the task defined on:
https://github.com/hypothesis/lms/pull/6832/files#diff-7baecd8f6812a5c2f1cc26796f8e93e4689ee5b8563575a58584e0c496c2e306R29

Schedule deletion of old EventData rows in LMS

---

h_periodic/h_beat.py

Refs https://github.com/hypothesis/h/issues/9291
Depends on https://github.com/hypothesis/h/pull/9458

Schedule deletion of expired task_done rows in h

---

Dockerfile
h_periodic/__init__.py
h_periodic/_version.py

Reverts hypothesis/h-periodic#549

Revert "Revert "Enable Sentry's "releases" feature""

---

.cookiecutter/cookiecutter.json
pyproject.toml

- **Apply updates from cookiecutter**
- **Don't let the cookiecutter update `_version.py`**

Sync with cookiecutter
